dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk11
      install: skip
      before_script: chmod +x gradlew
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Sleepy1221"
        - git config --local user.email "ImAnnoyed1245@gmail.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "build/libs/SpringMvcTemplate-0.0.1-SNAPSHOT.jar"
        skip_cleanup: true
    - stage: deploy to cf
      language: bash
      before_install:
        - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        - sudo apt-get update
        - sudo apt-get install cf-cli
        - sudo apt-get -y install jq
        - curl https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/5.2.1/flyway-commandline-5.2.1-linux-x64.tar.gz | tar xvz
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/SpringMvcTemplate/releases/download/$RELEASE_TAG/SpringMvcTemplate-0.0.1-SNAPSHOT.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      before_script:
        - cf login -a $CF_API_URL -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: $CF_SPACE   
